### ISSUE TITLE
Luigi's Mansion 3 Parse Error

### ISSUE THREAD

**Issue by Austin-Quick** [Vextil/Wwise-Unpacker#13]
I put "streamedfiles.pck" from LM3 into the "Game Files" folder and tried both the MP3 and OGG batch files. It will convert (extract?) to WAV files just fine, but when it tries to convert to MP3 or OGG, I get a parse error for each file. 
![Image 1](https://user-images.githubusercontent.com/31780736/77776248-157f0180-7024-11ea-98ab-ee206df75800.jpg)

Please let me know if there is something I'm doing wrong. Thanks in advance!

**Comment by mortalis13** [comment]
Seems these are errors of the `ww2ogg` conversion tool.  
Maybe it can't recognize the format of the WAVs.

The same error as in #18.
Check my [answer](https://github.com/Vextil/Wwise-Unpacker/issues/18#issuecomment-704291522) in that issue. I've created a fork of this repo that allows to extract WAV audio files.  
See if these can be played.
