### ISSUE TITLE
[SOLVED] Help needed with MGRR

### ISSUE THREAD

**Issue by doctorHOO** [Vextil/Wwise-Unpacker#39]
I'm trying to figure out how to dig into Metal Gear Rising: Revengeance's sound banks to extract several specific sound effects but can't seem to be able to find the fitting tools. Is it possible to somehow adapt Wwise-Unpacker to this task? The file extensions in question are .cpk and .wem, plus the .bnk files present in the game data are unreadable by Wwise-Unpacker for some reason.

**Comment by mortalis13** [comment]
If you have .wem files, try to search for info about how to convert them to playable audio.  
Like this page: https://www.gaminghouse.community/en/guides-tutorials-1003/how-to-play-convert-wem-files-ogg-mp3-67.  
Thus you can use the converting tools directly, maybe the latest versions will support the files you have.

**Comment by mortalis13** [comment]
Also you can check this project and try if it converts wem to wav:
https://github.com/vgmstream/vgmstream

Go to the section for Windows and download a zip with binaries, and it should contain the test.exe binary.
That's their cli console app that can be used for converting.

**Comment by doctorHOO** [comment]
That's the thing, I _can_ read .wem files in vgmstream-assisted foobar2000, but I suspect that each .wem might contain more than one track, and there's no way to tell whether that's the case or not. I have a grand total of 278 .wem files across all .cpk packages not containing voiceovers, and there don't seem to be any tools out there which would assist in mining out the sound table and unpacking it all correctly. What I'm looking for is _not_ among those .wem files, sadly.

**Comment by doctorHOO** [comment]
I've figured it out. The sound files I needed were buried deep within the main game archives, basically a deeply-nested container. Objective complete. :)
