### ISSUE TITLE
Missing Riff when trying to convert Alan Wake 2 .wem/.bnk files

### ISSUE THREAD

**Issue by RockettoDan** [Vextil/Wwise-Unpacker#40]
I get <img width="181" alt="Screenshot 2023-11-21 202959" src="https://github.com/Vextil/Wwise-Unpacker/assets/150630398/1bbc8197-6bfb-4872-acc1-c5afea82a89b"> when trying to unpack .wem and .bnk files from Alan Wake 2. Does anyone know how to fix this?

**Comment by mortalis13** [comment]
What is the original file type you feed into the script?
It only accepts pck and bnk.
If you have wem files directly, you can try using the vgmstream tool on them: https://vgmstream.org.
Or maybe an easier way would be using foobar2000 player with vgmstream plugin to play and convert those files.

**Comment by RockettoDan** [comment]
> What is the original file type you feed into the script? It only accepts pck and bnk. If you have wem files directly, you can try using the vgmstream tool on them: https://vgmstream.org. Or maybe an easier way would be using foobar2000 player with vgmstream plugin to play and convert those files.

Thank you for the information. I was able to convert the files.
