### ISSUE TITLE
Webroot detected this as a virus, false positive?

### ISSUE THREAD

**Issue by yellowface7** [Vextil/Wwise-Unpacker#6]
So right after I downloaded this, the antivirus software that I use, webroot seems to have detected something in this as a virus. I kinda think that it may be a false positive tho.

image link: http://s1291.photobucket.com/user/cheesyboyxyz/media/uh_zps4wzjztso.png.html?sort=3&o=0

**Comment by Vextil** [comment]
The bnkextr build comes from here: https://github.com/eXpl0it3r/bnkextr
Can't really see anything malicious, has to be a false positive.

**Comment by yellowface7** [comment]
I think that it is likely a false positive too. By the way, this works like a charm.

**Comment by Vextil** [comment]
I'm glad it works! I'll be closing this then, please let me know if any further issues show up.
